import React from 'react';
import { MarkdownUI } from './src/lib/MarkdownUI';

// This is a simple test example showing how the React component would be used
const ExampleApp: React.FC = () => {
  // Example HTML that would be generated by marked with markedUiExtension
  const exampleHtml = `
    <h1>Example Form</h1>
    <p>Fill out the form below:</p>
    <markdown-ui-widget id="name-input" content="eyJ0eXBlIjoidGV4dElucHV0IiwibGFiZWwiOiJOYW1lIiwicGxhY2Vob2xkZXIiOiJFbnRlciB5b3VyIG5hbWUifQ=="></markdown-ui-widget>
    <markdown-ui-widget id="choice-buttons" content="eyJ0eXBlIjoiYnV0dG9uR3JvdXAiLCJsYWJlbCI6IkNob29zZSBhbiBvcHRpb24iLCJjaG9pY2VzIjpbIk9wdGlvbiBBIiwiT3B0aW9uIEIiLCJPcHRpb24gQyJdfQ=="></markdown-ui-widget>
    <p>Thank you for filling out the form!</p>
  `;

  const handleWidgetEvent = (data: { id: string; value: any }) => {
    console.log('Widget event received:', data);
  };

  return (
    <div>
      <MarkdownUI html={exampleHtml} onWidgetEvent={handleWidgetEvent} />
    </div>
  );
};

export default ExampleApp;